<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Deporte', 'doctrine');

/**
 * BaseDeporte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_deporte
 * @property string $nombre_deporte
 * @property string $tipo_deporte
 * @property Doctrine_Collection $Persona
 * 
 * @method integer             getId_deporte()     Returns the current record's "id_deporte" value
 * @method string              getNombre_deporte() Returns the current record's "nombre_deporte" value
 * @method string              getTipo_deporTe()   Returns the current record's "tipo_deporte" value
 * @method Doctrine_Collection getPersona()        Returns the current record's "Persona" collection
 * @method Deporte             setId_deporte()     Sets the current record's "id_deporte" value
 * @method Deporte             setNombre_deporte() Sets the current record's "nombre_deporte" value
 * @method Deporte             setTipo_deporTe()   Sets the current record's "tipo_deporte" value
 * @method Deporte             setPersona()        Sets the current record's "Persona" collection
 * 
 * @package    reto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeporte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('deporte');
        $this->hasColumn('id_deporte', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_deporte', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('tipo_deporte', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Persona', array(
             'local' => 'id_deporte',
             'foreign' => 'id_deporte'));
    }
}