<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Persona', 'doctrine');

/**
 * BasePersona
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $apellido
 * @property string $celular
 * @property string $cedula
 * @property integer $id_mascota
 * @property integer $id_deporte
 * @property Deporte $Deporte
 * @property Mascota $Mascota
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getNombre()     Returns the current record's "nombre" value
 * @method string  getApellido()   Returns the current record's "apellido" value
 * @method string  getCelular()    Returns the current record's "celular" value
 * @method string  getCedula()     Returns the current record's "cedula" value
 * @method integer getId_mascota() Returns the current record's "id_mascota" value
 * @method integer getId_deporte() Returns the current record's "id_deporte" value
 * @method Deporte getDeporte()    Returns the current record's "Deporte" value
 * @method Mascota getMascota()    Returns the current record's "Mascota" value
 * @method Persona setId()         Sets the current record's "id" value
 * @method Persona setNombre()     Sets the current record's "nombre" value
 * @method Persona setApellido()   Sets the current record's "apellido" value
 * @method Persona setCelular()    Sets the current record's "celular" value
 * @method Persona setCedula()     Sets the current record's "cedula" value
 * @method Persona setId_mascota() Sets the current record's "id_mascota" value
 * @method Persona setId_deporte() Sets the current record's "id_deporte" value
 * @method Persona setDeporte()    Sets the current record's "Deporte" value
 * @method Persona setMascota()    Sets the current record's "Mascota" value
 * 
 * @package    reto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersona extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('persona');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('apellido', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('celular', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('cedula', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('id_mascota', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_deporte', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Deporte', array(
             'local' => 'id_deporte',
             'foreign' => 'id_deporte',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Mascota', array(
             'local' => 'id_mascota',
             'foreign' => 'id_mascota',
             'onDelete' => 'CASCADE'));
    }
}