<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/09/04 16:44:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=reto',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
