<?php

/**
 * DeporteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeporteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeporteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Deporte');
    }
}