Deporte:
  connection: doctrine
  tableName: deporte
  columns:
    id_deporte:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre_deporte:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tipo_deporte:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Persona:
      local: id_deporte
      foreign: id_deporte
      type: many
Mascota:
  connection: doctrine
  tableName: mascota
  columns:
    id_mascota:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre_mascota:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tipo_mascota:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Persona:
      local: id_mascota
      foreign: id_mascota
      type: many
Persona:
  connection: doctrine
  tableName: persona
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    apellido:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    celular:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    cedula:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_mascota:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_deporte:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Deporte: { onDelete: CASCADE, local: id_deporte, foreign: id_deporte, foreignAlias: Deportes}
    Mascota: { onDelete: CASCADE, local: id_mascota, foreign: id_mascota, foreignAlias: Mascotas}
